#!/bin/bash
########################################################################
#
#
#                       script: option-pstree
#                   adapted by: Dan Purgert    
#                  original by: Two_Dogs
#                      version: 0.1
#                         date: Sat Apr 23 10:12:35 EDT 2016
#                      purpose: Create a logfile of general process
#                             : information that will allow the linux
#                             : mint community members to assist the 
#                             : individual running it
#
#
#                      license: GPL v2 (only)
#                   repository: http://github.com/dpurgert
#              Two_Dogs source: http://github.com/two-dogs
#
#
########################################################################

if [ "$1" = "-h" ]; then
   printf "\n   option-pstree
   -------------

   This script will gather process related information which may 
   help the community troubleshoot the problem you are having.

   Options:
     -h    Print this help, and exit.
     -v    Verbose Mode.  Print to stdout and logfile

   USAGE:
     option-packages

   ------------- "

   exit 0
fi

exec 6>/dev/null 
if [ "$1" = "-v" ]; then
   #verbose   
   exec 6>&1
fi

# forbid execution as root.
if [[ $EUID -eq 0 ]]; then
   printf "\n\n===================WARNING!!!====================\n"
   printf "Detected script being run as root user.  It is not\n"
   printf "advisable to do so, as any errors in this script,\n"
   printf "or in the commands that do not require elevated\n"
   printf "privileges can potentially harm your system.\n\n"
   printf "This script is designed to only elevate your user\n"
   printf "priveleges for the command(s) that require it, and\n"
   printf "then drop back to your standard user.\n\n"
   printf "Exiting.\n"
   exit 1
fi


if [ "$1" != "-v" ]; then
   printf "\nQuiet Mode: Final notification until program completes."
   printf "\nDo not press any keys until prompted.\n"
fi


(
  date 
  printf "\n--OPTION PSTREE--\n\n--CHECK HDD EFI INFO--\n"
  [ -d /sys/firmware/efi ] && printf "\nEFI boot on HDD\n" \
   || printf "\nLegacy boot on HDD]n" 
  printf "\n--EFI INFO END--\n\n--INXI START--\n"
  inxi -c0 -F 
  printf "\n--INXI END--\n\n--PSTREE START--\n"
  sudo pstree -ansup 
  printf "\n--PSTREE END--\n\n"
  date
) | tee ~/option-pstree.log >&6 2>&1

printf "\n\n============================\n"
printf "COMPLETED! A copy has been saved to:\n"
printf "   $HOME/option-pstree.log\n"
printf "============================\n\n"

read -n1 -p "Share file to pastebin? [y|N]" "chk"

if [ "$chk" = "y" ] || [ "$chk" = "y" ];  then
   printf "\nProvide the following link to your helper:\n"
   printf "\n$(pastebin < ~/option-pstree.log)\n"
else
   printf "\nLogfile NOT uploaded to pastebin.\n"
   printf "Ask the person assisting you where to send it.\n"
fi

read -n1 -p "Remove the logfile? [y|N]" "chk"
if [ "$chk" = "y" ] || [ "$chk" = "Y" ];  then
   rm $HOME/option-pstree.log
   printf "\nLogfile removed.\n"
else
   printf "\nLogfile $HOME/option-pstree.log retained.\n"
fi
