#!/bin/bash
########################################################################
#
#
#                       script: option-print
#                   adapted by: Dan Purgert    
#                  original by: Two_Dogs
#                      version: 0.1
#                         date: Sat Apr 23 09:35:03 EDT 2016
#                      purpose: Create a logfile of general printer
#                             : settings that will allow the linux
#                             : mint community members to assist 
#                             : the individual running it.
#
#                      license: GPL v2 (only)
#                   repository: http://github.com/dpurgert
#              Two_Dogs source: http://github.com/two-dogs
#
#
########################################################################

if [ "$1" = "-h" ]; then
   printf "\n   option-print
   -------------

   This script will gather printer related information which may 
   help the community troubleshoot the problem you are having.

   Options:
     -h    Print this help, and exit.
     -v    Verbose Mode.  Print to stdout and logfile

   USAGE:
     option-system 

   ------------- "

   exit 0
fi

exec 6>/dev/null 
if [ "$1" = "-v" ]; then
   #verbose   
   exec 6>&1
fi

# forbid root execution.
if [[ $EUID -eq 0 ]]; then
   printf "\n\n===================WARNING!!!====================\n"
   printf "Detected script being run as root user.  It is not\n"
   printf "advisable to do so, as any errors in this script,\n"
   printf "or in the commands that do not require elevated\n"
   printf "privileges can potentially harm your system.\n\n"
   printf "This script is designed to only elevate your user\n"
   printf "priveleges for the command(s) that require it, and\n"
   printf "then drop back to your standard user.\n\n"
   printf "Exiting.\n"
   exit 1
fi


if [ "$1" != "-v" ]; then
   printf "\nQuiet Mode: Final notification until program completes."
   printf "\nDo not press any keys until prompted.\n"
fi


(
 date ;
 printf "\n--INXI BEGIN--\n"
 inxi -c0 -MS ;
 printf "\n--INXI END--\n\n--CHECK CUPS DAEMONS--\n"
 [ -e /var/run/cups/cupsd.pid ] && \
  printf "\nCUPS Daemon (cupsd) Running\n" \
  || printf "\nCUPS Daemon (cupsd) Stopped\n"
 if [ -e /var/run/cups/cups-browsed.pid ]; then
   printf "\nCUPS Bonjour Daemon (cups-browsed) Running\n" 
 else
   printf "\nCUPS Bonjour Daemon (cups-browsed) Stopped\n"
   printf "=================NOTE=====================\n"
   printf "not all systems seem to create the pidfile\n"
   printf "   /var/run/cups/cups-browsed\n"
   printf "Appears that it is running as $(pgrep cups-browsed)\n"
   printf "==========================================\n"
 fi
 printf "\n--CHECK CUPS COMPLETE--\n\n--SCANNER TEST START--\n"
 scanimage -L 
 printf "\n--SCANNER TEST COMPLETE--\n\n--CUPS ERROR LOG START--\n"
 cat /var/log/cups/error_log 
 printf "\n--CUPS ERROR LOG END--\n\n--SYSLOG CUPS ERRORS START--\n"
 grep -Ei 'error|fail|cups|colord' /var/log/syslog 
 printf "\n--SYSLOG CUPS ERRORS END--\n"
 date 
) | tee ~/option-print.log >&6 2>&1

printf "\n\n============================\n"
printf "COMPLETED! A copy has been saved to:\n"
printf "   $HOME/option-print.log\n"
printf "============================\n\n"

read -n1 -p "Share file to pastebin? [y|N]" "chk"

if [ "$chk" = "y" ] || [ "$chk" = "y" ];  then
   printf "\nProvide the following link to your helper:\n"
   printf "\n$(pastebin < ~/option-print.log)\n"
else
   printf "\nLogfile NOT uploaded to pastebin.\n"
   printf "Ask the person assisting you where to send it.\n"
fi

read -n1 -p "Remove the logfile? [y|N]" "chk"
if [ "$chk" = "y" ] || [ "$chk" = "Y" ];  then
   rm $HOME/option-print.log
   printf "\nLogfile removed.\n"
else
   printf "\nLogfile $HOME/option-print.log retained.\n"
fi
